[tool.poetry]
name = "sample-package-a"
version = "0.0.0"
description = "Sample Package A for demonstrating release-please automation"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "a", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.0"
pydantic = "^2.5.0"
httpx = "^0.25.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
black = "^23.9.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
mypy = "^1.6.0"

[tool.poetry.scripts]
sample-a = "a.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=a --cov-report=term-missing"
testpaths = ["tests"]